name: 'SWM GitHub Actions Basic'

on: push

jobs:
  build-test:
    name: 'Build & Test'

    runs-on: 'ubuntu-latest'

    steps:
    - name: Say Hello World 1 - ${{ matrix.os }}
      shell: bash
      run: |
       echo "OS: ${{ matrix.os }} "
       echo "nodejs version: ${{ matrix.nodejs }}"

  deploy-dev:
    name: 'Deploy to dev'

    needs:
      - build-test

    runs-on: 'ubuntu-latest'

    steps:
    - name: Say Hello World 1 - ${{ matrix.os }}
      shell: bash
      run: |
       echo "OS: ${{ matrix.os }} "
       echo "nodejs version: ${{ matrix.nodejs }}"

  deploy-staging1:
    name: 'Deploy to staging1'

    needs:
      - deploy-dev

    runs-on: 'ubuntu-latest'

    steps:
    - name: Say Hello World 1 - ${{ matrix.os }}
      shell: bash
      run: |
       echo "OS: ${{ matrix.os }} "
       echo "nodejs version: ${{ matrix.nodejs }}"

  deploy-staging2:
    name: 'Deploy to staging2'

    needs:
      - deploy-dev

    runs-on: 'ubuntu-latest'

    steps:
    - name: Say Hello World 1 - ${{ matrix.os }}
      shell: bash
      run: |
       echo "OS: ${{ matrix.os }} "
       echo "nodejs version: ${{ matrix.nodejs }}"

  deploy-prod:
    name: 'Deploy to prod'

    needs:
      - deploy-staging1
      - deploy-staging2

    runs-on: 'ubuntu-latest'

    steps:
    - name: Say Hello World 1 - ${{ matrix.os }}
      shell: bash
      run: |
       echo "OS: ${{ matrix.os }} "
       echo "nodejs version: ${{ matrix.nodejs }}"