name: 'SWM GitHub Actions Basic'

on: push

jobs:
  first-job:
    name: 'First Job'

    strategy:
      matrix:
        os: ['ubuntu-latest', 'windows-latest', 'macos-latest']

    runs-on: ${{ matrix.os }}

    steps:
    - name: Say Hello World 1 - ${{ matirx.os }}
      shell: bash
      run: |
       echo "OS: ${{ matrix.os }} "